--LOCK TYPE OPTIONS for cursors

--DEFAULT FOR FAST_FORWARD. CHANGES IN DB NOT MADE
DECLARE CURS CURSOR READ_ONLY
	FOR SELECT * FROM tblFilm

--AS SOON MOVE TO THE NEXT RECORD THEN THIS RECORD IS LOCKED AND CAN'T BE CHANGED
DECLARE CURS CURSOR SCROLL_LOCKS
	FOR SELECT * FROM tblFilm

--AS SOON AS YOU TRY AND MAKE A CHANGE AND UPDATE A RECORD IT 
--LOCKS THE RECORD THEN AND WILL FAIL IF CHANGES WERE MADE WHILE YOU WERE TRYING TO ACCESS IT
DECLARE CURS CURSOR OPTIMISTIC
	FOR SELECT * FROM tblFilm

--MORE DETAILS
--https://msdn.microsoft.com/en-gb/library/ms180169.aspx


--You can combine many combinations of options but you can't mix some