--Nested Transactions basics

BEGIN TRANSACTION Tran1

	PRINT @@TRANCOUNT

	--THE ROLLBACK ISSUE DESCRIBED BELOW CAN BE AVOIDED WITH THE USE OF SAVE POINTS
	--SAVE TRAN Tran2

	BEGIN TRANSACTION Tran2

		PRINT @@TRANCOUNT

	COMMIT TRAN Tran2
	--ROLLBACK TRAN Tran2
	--THIS WILL KEEP THE OUTER TRANSACTION ALIVE BECASUE SAVE WAS USED
	
	PRINT @@TRANCOUNT

COMMIT TRAN Tran1

--WHEN YOU ROLLBACK, IT ROLL BACKS ALL TRANSACTION!!
--EVEN THOUGH THIS TRAN2 WAS COMMITTED
	-- IF SAVEPOINT WAS USED IT AVOIDS THIS