USE MOVIES
GO
SET NOCOUNT ON

INSERT INTO tblActor(ActorID, ActorName)
VALUES(999, 'TEST ACTOR')

UPDATE tblActor
SET ActorDOB = GETDATE()
WHERE ActorID = 999

DELETE FROM tblActor
WHERE ActorID = 999