--This disables an arbitrary trigger it doesn't exist on the db

DISABLE TRIGGER NoChangesToTables ON DATABASE

--DO STUFF TO TABLES

ENABLE TRIGGER NoChangesToTables ON DATABASE

DISABLE TRIGGER ALL ON DATABASE
ENABLE TRIGGER ALL ON DATABASE
--APPLIES TO ALL OF THE TRIGGERS